### ISSUE TITLE
Any reference for this repo?

### ISSUE THREAD

**Issue by hitdshu** [Shepherddot/large_scale_monocular_dense_mapping#1]
Hi,

The result looks very interesting. Could you please provide some references for it? Thanks.

Deshun

**Comment by Shepherddot** [comment]
我已收到，我会尽快查看的

**Comment by Shepherddot** [comment]
hello, this repo is related to monocular depth estimation, such as manydepth[1], however, i use poses comes from orb slam2 to predict current image depth. Then we can use some algorithms to fuse multiple depth images, such as remode[2], treat the parameter of the probabilistic carefully.

[1] https://github.com/nianticlabs/manydepth
[2] https://github.com/uzh-rpg/rpg_open_remode
